# Generated by Django 3.2 on 2022-01-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assetstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(choices=[('BTC', 'Bitcoin'), ('LINK', 'Chainlink'), ('XRP', 'XRP'), ('LTC', 'Litecoin'), ('CHZ', 'Chiliz'), ('ETH', 'Ethereum'), ('DOGE', 'Dogecoin'), ('ADA', 'Cardano')], default='BTC', max_length=100)),
                ('sell', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor de venda')),
                ('buy', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor de compra')),
                ('timer', models.IntegerField(choices=[(5, '5'), (10, '10'), (20, '20'), (30, '30'), (60, '60')], default=30, verbose_name='Escolha um timer de alerta (mins)')),
                ('user_id', models.ManyToManyField(to='clients.Clientstable', verbose_name='Cliente')),
            ],
        ),
    ]
