# Generated by Django 3.2 on 2022-01-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20220120_2246'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetstable',
            options={'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.AlterField(
            model_name='assetstable',
            name='timer',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (20, '20'), (30, '30'), (60, '60')], default=30, verbose_name='Timer de alerta (mins)'),
        ),
        migrations.RemoveField(
            model_name='assetstable',
            name='user_id',
        ),
        migrations.AddField(
            model_name='assetstable',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientstable', verbose_name='Cliente'),
        ),
    ]
