# Generated by Django 3.2 on 2022-01-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20220120_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstable',
            name='nameconfig',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome da configuração'),
        ),
    ]
