# Generated by Django 3.2 on 2022-01-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetstable_nameconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstable',
            name='buy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor de compra'),
        ),
        migrations.AlterField(
            model_name='assetstable',
            name='nameconfig',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da configuração'),
        ),
        migrations.AlterField(
            model_name='assetstable',
            name='sell',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor de venda'),
        ),
    ]
