# Generated by Django 3.2 on 2022-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_assetstable_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstable',
            name='dateemail',
            field=models.DateField(blank=True, null=True),
        ),
    ]
