# Generated by Django 3.2 on 2022-02-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assetstable_dateemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetstable',
            old_name='dateemail',
            new_name='emaildate',
        ),
    ]
