# Generated by Django 3.2 on 2022-02-03 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_rename_dateemail_assetstable_emaildate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstable',
            name='emaildate',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 18, 47, 48, 262005)),
        ),
    ]
