# Generated by Django 3.2 on 2022-02-04 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_assetstable_emaildate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstable',
            name='emaildate',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 22, 3, 21, 269808)),
        ),
    ]
