# Generated by Django 3.2 on 2022-02-04 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_remove_assetstable_emaildate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstable',
            name='emaildate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
