# Generated by Django 3.2 on 2022-02-05 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_alter_assetstable_emaildate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstable',
            name='emaildate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
