# Generated by Django 3.2 on 2022-01-18 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='Nascimento')),
                ('insc', models.DateField(default=django.utils.timezone.now, verbose_name='Data de inscrição')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Profissão')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('tel', models.CharField(help_text='Telefone', max_length=11, unique=True, verbose_name='Telefone (1)')),
            ],
        ),
    ]
