# Generated by Django 3.2 on 2022-01-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientstable',
            options={'ordering': ('-insc',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='clientstable',
            name='tel',
            field=models.CharField(max_length=11, unique=True, verbose_name='Telefone'),
        ),
    ]
